name: edirnebenim
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'







dependencies:
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  flutter_local_notifications: ^13.0.0
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  get_it: ^7.2.0
  go_router: ^6.5.0
  google_fonts: ^4.0.3
  iconsax: ^0.0.8
  image_cropper: ^3.0.1
  image_picker: ^0.8.7
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.2
  loading_animation_widget: ^1.2.0+4
  multi_value_listenable_builder: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1




flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/categories/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
